version: '3'
services:
  postgres:
    image: postgres:13 # https://hub.docker.com/_/postgres
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=mydatabase
    volumes:
    - ./db_data:/var/lib/postgresql/data
  pgadmin:
        image: dpage/pgadmin4
    depends_on: 
      - postgres
    ports:
      - "53603:53603"
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: talktobhargav@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root

volumes:
  db_data: