version: '3'
services:
  pg:
    image: postgres:11-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=mydatabase
    volumes:
    - ./db_data:/var/lib/postgresql/data
